

services:
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=helpboard
      - POSTGRES_USER=helpboard
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - helpboard-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U helpboard -d helpboard"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://helpboard:${POSTGRES_PASSWORD}@postgres:5432/helpboard
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PORT=5000
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - helpboard-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - helpboard-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  postgres_data:

networks:
  helpboard-network:
    driver: bridge